### ISSUE TITLE
Error while testing

### ISSUE THREAD

**Issue by quicktwit** [mabaorui/OnSurfacePrior#4]
Hi
Thank you again for this research work.
So I could train perfectly using default parameters.
Now when I run test to create mesh, I am getting this error:
```
Traceback (most recent call last):
  File "onSurPrior.py", line 833, in <module>
    vertices, triangles, _, _ = marching_cubes_lewiner(vox, thresh)
  File "/usr/local/lib/python3.7/dist-packages/skimage/measure/_marching_cubes_lewiner.py", line 135, in marching_cubes_lewiner
    raise ValueError("Surface level must be within volume data range.")
ValueError: Surface level must be within volume data range.
```
How do I fix this? Thank you in advance.

**Comment by mabaorui** [comment]
Hi,
Are there any other outputs during the test?

**Comment by quicktwit** [comment]
Hi
Thank you for your response.
This is how I ran:
`python onSurPrior.py --data_dir ./data/ --out_dir ./train_net/ --CUDA 0 --INPUT_NUM 84747 --epoch 30000 --input_ply_file input_1.ply --test`


This is whole log:
```
2022-07-06 06:12:27.620822: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /home/username/anaconda3/envs/tf_onsurface/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From /home/username/anaconda3/envs/tf_onsurface/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py:464: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

2022-07-06 06:12:28.864861: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2022-07-06 06:12:28.872446: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:28.872538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
2022-07-06 06:12:28.872556: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2022-07-06 06:12:28.875414: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2022-07-06 06:12:28.875445: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2022-07-06 06:12:28.892467: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcufft.so.10
2022-07-06 06:12:28.892646: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcurand.so.10
2022-07-06 06:12:28.893039: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusolver.so.11
2022-07-06 06:12:28.893517: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcusparse.so.11
2022-07-06 06:12:28.893625: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudnn.so.8
2022-07-06 06:12:28.893696: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:28.893798: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:28.893854: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2022-07-06 06:12:28.894049: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-06 06:12:28.894947: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:28.895011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
2022-07-06 06:12:28.895054: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:28.895146: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:28.895197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2022-07-06 06:12:28.895217: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2022-07-06 06:12:29.204529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-07-06 06:12:29.204551: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2022-07-06 06:12:29.204556: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2022-07-06 06:12:29.204678: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:29.204795: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:29.204882: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:29.204952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 22010 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6)
WARNING:tensorflow:From onSurPrior.py:493: DatasetV1.make_initializable_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
This is a deprecated API that should only be used in TF 1 graph mode and legacy TF 2 graph mode available through `tf.compat.v1`. In all other situations -- namely, eager mode and inside `tf.function` -- you can consume dataset elements using `for elem in dataset: ...` or by explicitly creating iterator via `iterator = iter(dataset)` and fetching its elements via `values = next(iterator)`. Furthermore, this API is not available in TF 2. During the transition from TF 1 to TF 2 you can use `tf.compat.v1.data.make_initializable_iterator(dataset)` to create a TF 1 graph mode style iterator for a dataset created through TF 2 APIs. Note that this should be a transient state of your code base as there are in general no guarantees about the interoperability of TF 1 and TF 2 code.
SHAPE_NUM: 3
/home/username/anaconda3/envs/tf_onsurface/lib/python3.6/site-packages/tensorflow/python/keras/legacy_tf_layers/core.py:171: UserWarning: `tf.layers.dense` is deprecated and will be removed in a future version. Please use `tf.keras.layers.Dense` instead.
  warnings.warn('`tf.layers.dense` is deprecated and '
/home/username/anaconda3/envs/tf_onsurface/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
net: Tensor("global/concat:0", shape=(4096, 640), dtype=float32)
net: Tensor("global/decoder/resnetBlockFC_7/dense/BiasAdd:0", shape=(4096, 512), dtype=float32)
grad [<tf.Tensor 'global/gradients/global/dense_1/MatMul_grad/MatMul:0' shape=(4096, 3) dtype=float32>]
Tensor("global/gradients/global/dense_1/MatMul_grad/MatMul:0", shape=(4096, 3), dtype=float32)
normal_p_lenght Tensor("global/ExpandDims:0", shape=(4096, 1), dtype=float32)
grad_norm Tensor("global/truediv:0", shape=(4096, 3), dtype=float32)
g_points: Tensor("global/sub:0", shape=(4096, 3), dtype=float32)
WARNING:tensorflow:From /home/username/anaconda3/envs/tf_onsurface/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:206: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
g_points_knn: Tensor("GatherV2:0", shape=(1, 4096, 50, 3), dtype=float32)
g_points_knn: Tensor("Reshape_6:0", shape=(4096, 50, 3), dtype=float32)
rotate_p: Tensor("Tile:0", shape=(4096, 50, 3), dtype=float32)
feature_f: Tensor("pointnet/Relu:0", shape=(4096, 512), dtype=float32)
pointnet: Tensor("pointnet/dense_1/BiasAdd:0", shape=(4096, 512), dtype=float32)
g_points_knn: Tensor("GatherV2_1:0", shape=(1, 4096, 50, 3), dtype=float32)
g_points_knn: Tensor("Reshape_12:0", shape=(4096, 50, 3), dtype=float32)
rotate_p: Tensor("Tile_1:0", shape=(4096, 50, 3), dtype=float32)
feature_f: Tensor("pointnet_1/Relu:0", shape=(4096, 512), dtype=float32)
pointnet: Tensor("pointnet_1/dense_1/BiasAdd:0", shape=(4096, 512), dtype=float32)
feature_f: Tensor("pointnet_2/Relu:0", shape=(4096, 512), dtype=float32)
pointnet: Tensor("pointnet_2/dense_1/BiasAdd:0", shape=(4096, 512), dtype=float32)
2022-07-06 06:12:30.343320: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:30.343409: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 23.69GiB deviceMemoryBandwidth: 871.81GiB/s
2022-07-06 06:12:30.343466: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:30.343544: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:30.343593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0
2022-07-06 06:12:30.343612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-07-06 06:12:30.343617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 
2022-07-06 06:12:30.343620: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N 
2022-07-06 06:12:30.343671: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:30.343752: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-06 06:12:30.343809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 22010 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6)
feature_bs: (2000, 2000)
test start
128
2022-07-06 06:12:30.391662: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3699850000 Hz
[1.05      0.8021808 0.5021474]
[-0.05 -0.05 -0.05]
2022-07-06 06:12:34.425492: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2022-07-06 06:12:35.030397: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2022-07-06 06:12:35.030442: I tensorflow/stream_executor/cuda/cuda_blas.cc:18
38] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
max_min: 0.34844363 -0.002008438 0.02327601
602983 1494169
Traceback (most recent call last):
  File "onSurPrior.py", line 837, in <module>
    vertices, triangles, _, _ = marching_cubes_lewiner(vox, thresh)
  File "/home/username/anaconda3/envs/tf_onsurface/lib/python3.6/site-packages/skimage/measure/_marching_cubes_lewiner.py", line 135, in marching_cubes_lewiner
    raise ValueError("Surface level must be within volume data range.")
ValueError: Surface level must be within volume data range.
```

**Comment by mabaorui** [comment]
Hi,
You can try changing this line of code to ‘ threshs = [-0.005,0.0,0.005] ’
https://github.com/mabaorui/OnSurfacePrior/blob/d53bf3a7bc88837e2974ddc1fd0700ecc2641ade/onSurPrior.py#L825

**Comment by quicktwit** [comment]
Hi @mabaorui 
I got same error for these ‘ threshs = [-0.005,0.0,0.005] ’
`feature_bs: (2000, 2000)
test start
128
voxel size = 128
2022-07-07 05:56:33.190316: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3699850000 Hz
bd_max = [1.05      0.8021808 0.5021474]
bd_min  = [-0.05 -0.05 -0.05]
2022-07-07 05:56:37.543012: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2022-07-07 05:56:38.203275: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublasLt.so.11
2022-07-07 05:56:38.203321: I tensorflow/stream_executor/cuda/cuda_blas.cc:1838] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
max_min: 0.34844363 -0.002008438 0.02327601
2097152 0
694166 1402986
602983 1494169
Traceback (most recent call last):
  File "onSurPrior.py", line 844, in <module>
    vertices, triangles, _, _ = marching_cubes_lewiner(vox, thresh)
  File "/home/username/anaconda3/envs/tf_onsurface/lib/python3.6/site-packages/skimage/measure/_marching_cubes_lewiner.py", line 135, in marching_cubes_lewiner
    raise ValueError("Surface level must be within volume data range.")
ValueError: Surface level must be within volume data range.`

**Comment by mabaorui** [comment]
Hi,
Please check if any meshes have been created in the ' --out_dir ' .

**Comment by quicktwit** [comment]
Yes, meshes are created in the output directory. I will close this issue for now. If I will find any solution for this error, I will create a new issue and provide that. Thank you again @mabaorui
